### ISSUE TITLE
Particle tracking and support for high-order meshes?

### ISSUE THREAD

**Issue by jmmaljaars** [LEoPart-project/leopart-x#8]
We should open the discussion on whether we intend to support high-order meshes in the long term, as this will affect the choice for the particle tracking. There seem to be two paths:

- do the particle tracking directly on the high-order mesh. (the *convex polyhedron* particle tracking does not seem apt to handle this)
- map to parent cell and do the advection on a reference element (requires a back-and-forth mapping of particle positions between the parent and the physical domain)

**Comment by nate-sime** [comment]
Implemented in #20
