### ISSUE TITLE
Generalize Runge-Kutta advection via Butcher Tableau

### ISSUE THREAD

**Issue by jmmaljaars** [LEoPart-project/leopart-x#9]
Related to issue #3: we may consider to allow the user to specify their own (explicit) Runge-Kutta advection scheme by providing a Butcher Tableau. 

(Euler, RK2 and RK4 are then just pre-programmed specializations that are provided for convenience)

**Comment by nate-sime** [comment]
Addressed in #20 for explicit RK methods.

**Comment by nate-sime** [comment]
Implemented in #20
